name: "etl"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *" # Triggers every hour at 15th minute.
env:
  APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
  APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
  BUCKET_DIR: ${{ github.workspace }}/bucket
  REMOTE_CDN_PUBLIC_URL: ${{ secrets.REMOTE_CDN_PUBLIC_URL }}
  REMOTE_CDN_ENDPOINT_URL: ${{ secrets.REMOTE_CDN_ENDPOINT_URL }}
  REMOTE_CDN_BUCKET_NAME: ${{ secrets.REMOTE_CDN_BUCKET_NAME }}
  REMOTE_CDN_ACCESS_KEY_ID: ${{ secrets.REMOTE_CDN_ACCESS_KEY_ID }}
  REMOTE_CDN_SECRET_ACCESS_KEY: ${{ secrets.REMOTE_CDN_SECRET_ACCESS_KEY }}
  DB_CONNECTION_URL: ${{ secrets.DB_CONNECTION_URL }}
concurrency:
  group: etl
  cancel-in-progress: false
jobs:
  # Simple job to check supabase project status and keep it active.
  check_supabase_status:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H 'Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}' '${{ secrets.SUPABASE_PROJECT_URL }}/functions/v1/return-ok'

  run_controller:
    runs-on: ubuntu-latest
    outputs:
      meta: ${{ steps.out.outputs.meta }}
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:run_controller
      - run: |
          cd bucket
          git config user.name capflake-bot
          git config user.email capflake-bot@users.noreply.github.com
          git add --all
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit. Skipping pull and push."
          else
            git commit -m "[AUTO] run_controller $(date)"
            git pull --rebase && git push --force-with-lease
          fi
      - id: out
        run: echo meta=$(cat $BUCKET_DIR/controller.json) >> $GITHUB_OUTPUT

  load_sector_data:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_sector_data.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_sector_data
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_sector_data $(date)"

  load_index_data:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_index_data.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_index_data
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_index_data $(date)"

  load_ticker_profile:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_ticker_profile.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_ticker_profile
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_ticker_profile $(date)"

  load_ticker_data:
    needs: [run_controller, load_ticker_profile]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_ticker_data.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_ticker_data
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_ticker_data $(date)"

  load_ticker_screener:
    # "load_ticker_screener" needs to rely on "load_ticker_data" to avoid
    # throttling as they use the same source.
    needs: [run_controller, load_ticker_profile, load_ticker_data]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_ticker_screener.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_ticker_screener
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_ticker_screener $(date)"

  load_ticker_logo:
    needs: [run_controller, load_ticker_profile]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_ticker_logo.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_ticker_logo
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_ticker_logo $(date)" --skip_no_changes

  # This job should always run after `load_ticker_logo`.
  load_ticker_logo_remote:
    needs: [run_controller, load_ticker_logo]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_ticker_logo_remote
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_ticker_logo_remote $(date)"

  load_ticker_news:
    needs: [run_controller, load_ticker_profile]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_ticker_news.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_ticker_news
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_ticker_news $(date)"

  load_market_calendar:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_market_calendar.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_market_calendar
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_market_calendar $(date)"

  load_economic_calendar:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_economic_calendar.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_economic_calendar
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_economic_calendar $(date)"

  load_earnings_calendar:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_earnings_calendar.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_earnings_calendar
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_earnings_calendar $(date)"

  load_dividends_calendar:
    needs: [run_controller]
    if: ${{ !failure() && !cancelled() && fromJSON(needs.run_controller.outputs.meta).load_dividends_calendar.runnable }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_dividends_calendar
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_dividends_calendar $(date)"

  load_database:
    needs: [
      run_controller,
      load_sector_data,
      load_index_data,
      load_ticker_profile,
      load_ticker_data,
      load_ticker_screener,
      load_ticker_logo,
      load_ticker_logo_remote,
      load_ticker_news,
      load_market_calendar,
      load_economic_calendar,
      load_earnings_calendar,
      load_dividends_calendar,
    ]
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_database
