name: "etl_financial_events"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 */6 * * *" # Triggers 4 times every day.
env:
  BUCKET_DIR: ${{ github.workspace }}/bucket
concurrency:
  group: etl_financial_events
  cancel-in-progress: false
jobs:
  load_earnings_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_earnings_calendar
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_earnings_calendar $(date)"

  load_dividends_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_dividends_calendar
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_dividends_calendar $(date)"

  load_stock_splits:
    runs-on: ubuntu-latest
    steps:
      - uses: capflake/setup-bazel@v1
      - uses: actions/checkout@v4
        with:
          repository: capflake/nebula
          token: ${{ secrets.GH_PAT }}
          path: nebula
      - uses: actions/checkout@v4
        with:
          repository: capflake/bucket
          token: ${{ secrets.GH_PAT }}
          path: bucket
      - run: cd nebula && bazel run //etl:load_stock_splits
      - run: cd nebula && bazel run //etl:commit_rebase_push -- --git_repo=${{ github.workspace }}/bucket --commit_message="[AUTO] load_stock_splits $(date)"
