name: "Load mongo"
on: workflow_dispatch
jobs:
  load_mongo:
    name: "Load mongo"
    runs-on: ubuntu-latest
    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: capflake/cap-daemon
          token: ${{ secrets.GH_PAT }}
          path: cap-daemon
      - uses: actions/checkout@v3
        with:
          repository: capflake/internal-assets
          token: ${{ secrets.GH_PAT }}
          path: internal-assets
      - uses: actions/checkout@v3
        with:
          repository: capflake/assets
          token: ${{ secrets.GH_PAT }}
          path: assets
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipenv
      - name: Prepare cap-daemon
        run: |
          cd cap-daemon
          pipenv sync
      - name: Load mongo
        run: |
          cd cap-daemon
          bin/load_symbol_info --internal_assets_path ../internal-assets --assets_path ../assets
