name: "Load news"
on: workflow_dispatch
jobs:
  etl_news:
    name: "Load news"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: capflake/cap-daemon
          token: ${{ secrets.GH_PAT }}
          path: cap-daemon
      - uses: actions/checkout@v3
        with:
          repository: capflake/internal-assets
          token: ${{ secrets.GH_PAT }}
          path: internal-assets
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipenv
      - name: Prepare internal-assets
        run: |
          mkdir -p internal-assets/news
      - name: Prepare cap-daemon
        run: |
          cd cap-daemon
          pipenv sync
      - name: Load news
        run: |
          cd cap-daemon
          bin/etl_news --target=../internal-assets/news --assets_txt=../internal-assets/assets.txt
      - name: Commit changes
        run: |
          cd internal-assets
          git config user.name capflake-bot
          git config user.email capflake-bot@users.noreply.github.com
          git add --all
          git commit --allow-empty -m "[AUTO] update news $(date)"
          git push
