name: "Load data"
on:
  workflow_dispatch:
  schedule:
    # Trigger every day at 08:15, 20:15
    - cron: "15 9,21 * * *"
jobs:
  etl_assets:
    name: "Load assets"
    runs-on: ubuntu-latest
    env:
      ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
      ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
      ALPACA_API_URL: ${{ secrets.ALPACA_API_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: capflake/cap-daemon
          token: ${{ secrets.GH_PAT }}
          path: cap-daemon
      - uses: actions/checkout@v3
        with:
          repository: capflake/internal-assets
          token: ${{ secrets.GH_PAT }}
          path: internal-assets
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipenv
      - name: Prepare internal-assets
        run: |
          mkdir -p internal-assets/info
      - name: Prepare cap-daemon
        run: |
          cd cap-daemon
          pipenv sync
      - name: Load assets
        run: |
          cd cap-daemon
          bin/etl_assets --target=../internal-assets/info --gen_assets_dir=../internal-assets
      - name: Commit changes
        run: |
          cd internal-assets
          git config user.name capflake-bot
          git config user.email capflake-bot@users.noreply.github.com
          git add --all
          git commit --allow-empty -m "[AUTO] update assets $(date)"
          git push
  etl_news:
    name: "Load news"
    runs-on: ubuntu-latest
    needs: etl_assets
    steps:
      - uses: actions/checkout@v3
        with:
          repository: capflake/cap-daemon
          token: ${{ secrets.GH_PAT }}
          path: cap-daemon
      - uses: actions/checkout@v3
        with:
          repository: capflake/internal-assets
          token: ${{ secrets.GH_PAT }}
          path: internal-assets
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipenv
      - name: Prepare internal-assets
        run: |
          mkdir -p internal-assets/news
      - name: Prepare cap-daemon
        run: |
          cd cap-daemon
          pipenv sync
      - name: Load news
        run: |
          cd cap-daemon
          bin/etl_news --target=../internal-assets/news --assets_txt=../internal-assets/assets.txt
      - name: Commit changes
        run: |
          cd internal-assets
          git config user.name capflake-bot
          git config user.email capflake-bot@users.noreply.github.com
          git add --all
          git commit --allow-empty -m "[AUTO] update news $(date)"
          git push
  etl_earnings:
    name: "Load earnings"
    runs-on: ubuntu-latest
    needs: [etl_assets, etl_news]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: capflake/cap-daemon
          token: ${{ secrets.GH_PAT }}
          path: cap-daemon
      - uses: actions/checkout@v3
        with:
          repository: capflake/internal-assets
          token: ${{ secrets.GH_PAT }}
          path: internal-assets
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipenv
      - name: Prepare internal-assets
        run: |
          mkdir -p internal-assets/earnings
      - name: Prepare cap-daemon
        run: |
          cd cap-daemon
          pipenv sync
      - name: Load earnings
        run: |
          cd cap-daemon
          bin/etl_earnings --target=../internal-assets/earnings --assets_txt=../internal-assets/assets.txt
      - name: Commit changes
        run: |
          cd internal-assets
          git config user.name capflake-bot
          git config user.email capflake-bot@users.noreply.github.com
          git add --all
          git commit --allow-empty -m "[AUTO] update earnings $(date)"
          git push
  etl_logo:
    name: "Load logo"
    runs-on: ubuntu-latest
    needs: etl_assets
    steps:
      - uses: actions/checkout@v3
        with:
          repository: capflake/cap-daemon
          token: ${{ secrets.GH_PAT }}
          path: cap-daemon
      - uses: actions/checkout@v3
        with:
          repository: capflake/internal-assets
          token: ${{ secrets.GH_PAT }}
          path: internal-assets
      - uses: actions/checkout@v3
        with:
          repository: capflake/assets
          token: ${{ secrets.GH_PAT }}
          path: assets
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python3 -m pip install --user pipenv
      - name: Prepare assets
        run: |
          mkdir -p assets/logo
      - name: Prepare cap-daemon
        run: |
          cd cap-daemon
          pipenv sync
      - name: Load logo
        run: |
          cd cap-daemon
          bin/etl_logo --target=../assets/logo --assets_txt=../internal-assets/assets.txt
      - name: Commit changes
        run: |
          cd assets
          git config user.name capflake-bot
          git config user.email capflake-bot@users.noreply.github.com
          git add --all
          git commit --allow-empty -m "[AUTO] update logo $(date)"
          git push
